package com.zhongan.icare.message.push.dao.dataobject;

import com.zhongan.health.common.share.bean.BaseDataObject;

public class PushTemplateDO extends BaseDataObject
{
    private static final long serialVersionUID = 1481255861528L;

    /**
     * 服务端模板编码
     *
     * @mbggenerated
     */
    private String code;

    /**
     * 组的编号
     *
     * @mbggenerated
     */
    private String groupCode;

    /**
     * 名称
     *
     * @mbggenerated
     */
    private String name;

    /**
     * 描述
     *
     * @mbggenerated
     */
    private String description;

    /**
     * 消息显示样式(0：文本，1：文本+图片，2：超链接)
     *
     * @mbggenerated
     */
    private Integer msgLayout;

    /**
     * 消息的模板字段，JSON数据
     *
     * @mbggenerated
     */
    private String msgModel;

    /**
     * 属于
     */
    private Long belong;

    public Long getBelong()
    {
        return belong;
    }

    public void setBelong(Long belong)
    {
        this.belong = belong;
    }

    /**
     * This method returns the value of the database column push_template.code
     *
     * @return the value of push_template.code
     * @mbggenerated
     */
    public String getCode()
    {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_template.code
     *
     * @param code the value for push_template.code
     * @mbggenerated
     */
    public void setCode(String code)
    {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method returns the value of the database column push_template.group_code
     *
     * @return the value of push_template.group_code
     * @mbggenerated
     */
    public String getGroupCode()
    {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_template.group_code
     *
     * @param groupCode the value for push_template.group_code
     * @mbggenerated
     */
    public void setGroupCode(String groupCode)
    {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method returns the value of the database column push_template.name
     *
     * @return the value of push_template.name
     * @mbggenerated
     */
    public String getName()
    {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_template.name
     *
     * @param name the value for push_template.name
     * @mbggenerated
     */
    public void setName(String name)
    {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method returns the value of the database column push_template.description
     *
     * @return the value of push_template.description
     * @mbggenerated
     */
    public String getDescription()
    {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_template.description
     *
     * @param description the value for push_template.description
     * @mbggenerated
     */
    public void setDescription(String description)
    {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method returns the value of the database column push_template.msg_layout
     *
     * @return the value of push_template.msg_layout
     * @mbggenerated
     */
    public Integer getMsgLayout()
    {
        return msgLayout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_template.msg_layout
     *
     * @param msgLayout the value for push_template.msg_layout
     * @mbggenerated
     */
    public void setMsgLayout(Integer msgLayout)
    {
        this.msgLayout = msgLayout;
    }

    /**
     * This method returns the value of the database column push_template.msg_model
     *
     * @return the value of push_template.msg_model
     * @mbggenerated
     */
    public String getMsgModel()
    {
        return msgModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_template.msg_model
     *
     * @param msgModel the value for push_template.msg_model
     * @mbggenerated
     */
    public void setMsgModel(String msgModel)
    {
        this.msgModel = msgModel == null ? null : msgModel.trim();
    }
}