package com.zhongan.icare.message.push.dao.dataobject;

import java.util.Date;

import com.zhongan.health.common.share.bean.BaseDataObject;

public class SmsLogDO extends BaseDataObject {
    private static final long serialVersionUID = 1492595383631L;

    /**
     * 短信模板
     *
     * @mbggenerated
     */
    private String            templateNo;

    /**
     * 发送的参数
     *
     * @mbggenerated
     */
    private String            param;

    /**
     * 短信接收人
     *
     * @mbggenerated
     */
    private Long              receiverCustId;

    /**
     * 短信接收人手机号
     *
     * @mbggenerated
     */
    private String            receiverPhone;

    /**
     * 短信发送返回的code
     *
     * @mbggenerated
     */
    private String            resultCode;

    /**
     * 短信发送返回的message
     *
     * @mbggenerated
     */
    private String            resultMessage;

    /**
     * 发送时间
     *
     * @mbggenerated
     */
    private Date              sendeTime;

    /**
     * 发送类型(1-实时,2-定时)
     *
     * @mbggenerated
     */
    private Integer           sendType;

    /**
     * 所属公司
     *
     * @mbggenerated
     */
    private Long              orgCustId;
    private Long              batchId;

    public Long getBatchId() {
        return batchId;
    }

    public void setBatchId(Long batchId) {
        this.batchId = batchId;
    }

    /**
     * This method returns the value of the database column sms_log.template_no
     *
     * @return the value of sms_log.template_no
     * @mbggenerated
     */
    public String getTemplateNo() {
        return templateNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sms_log.template_no
     *
     * @param templateNo the value for sms_log.template_no
     * @mbggenerated
     */
    public void setTemplateNo(String templateNo) {
        this.templateNo = templateNo == null ? null : templateNo.trim();
    }

    /**
     * This method returns the value of the database column sms_log.param
     *
     * @return the value of sms_log.param
     * @mbggenerated
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sms_log.param
     *
     * @param param the value for sms_log.param
     * @mbggenerated
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method returns the value of the database column
     * sms_log.receiver_cust_id
     *
     * @return the value of sms_log.receiver_cust_id
     * @mbggenerated
     */
    public Long getReceiverCustId() {
        return receiverCustId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sms_log.receiver_cust_id
     *
     * @param receiverCustId the value for sms_log.receiver_cust_id
     * @mbggenerated
     */
    public void setReceiverCustId(Long receiverCustId) {
        this.receiverCustId = receiverCustId;
    }

    /**
     * This method returns the value of the database column
     * sms_log.receiver_phone
     *
     * @return the value of sms_log.receiver_phone
     * @mbggenerated
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sms_log.receiver_phone
     *
     * @param receiverPhone the value for sms_log.receiver_phone
     * @mbggenerated
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone == null ? null : receiverPhone.trim();
    }

    /**
     * This method returns the value of the database column sms_log.result_code
     *
     * @return the value of sms_log.result_code
     * @mbggenerated
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sms_log.result_code
     *
     * @param resultCode the value for sms_log.result_code
     * @mbggenerated
     */
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode == null ? null : resultCode.trim();
    }

    /**
     * This method returns the value of the database column
     * sms_log.result_message
     *
     * @return the value of sms_log.result_message
     * @mbggenerated
     */
    public String getResultMessage() {
        return resultMessage;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sms_log.result_message
     *
     * @param resultMessage the value for sms_log.result_message
     * @mbggenerated
     */
    public void setResultMessage(String resultMessage) {
        this.resultMessage = resultMessage == null ? null : resultMessage.trim();
    }

    /**
     * This method returns the value of the database column sms_log.sende_time
     *
     * @return the value of sms_log.sende_time
     * @mbggenerated
     */
    public Date getSendeTime() {
        return sendeTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sms_log.sende_time
     *
     * @param sendeTime the value for sms_log.sende_time
     * @mbggenerated
     */
    public void setSendeTime(Date sendeTime) {
        this.sendeTime = sendeTime;
    }

    /**
     * This method returns the value of the database column sms_log.send_type
     *
     * @return the value of sms_log.send_type
     * @mbggenerated
     */
    public Integer getSendType() {
        return sendType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sms_log.send_type
     *
     * @param sendType the value for sms_log.send_type
     * @mbggenerated
     */
    public void setSendType(Integer sendType) {
        this.sendType = sendType;
    }

    /**
     * This method returns the value of the database column sms_log.org_cust_id
     *
     * @return the value of sms_log.org_cust_id
     * @mbggenerated
     */
    public Long getOrgCustId() {
        return orgCustId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sms_log.org_cust_id
     *
     * @param orgCustId the value for sms_log.org_cust_id
     * @mbggenerated
     */
    public void setOrgCustId(Long orgCustId) {
        this.orgCustId = orgCustId;
    }
}
