package com.zhongan.icare.message.push.dao.dataobject;

import com.zhongan.health.common.share.bean.BaseDataObject;

public class MsgPushDO extends BaseDataObject {
    private Long    custId;

    private String  tagName;

    private Integer messageType;

    private Integer messageLayout;

    private String  messageTitle;

    private String  messageDetail;

    private String  messageIcon;

    private Integer start;

    private Integer end;

    /**
     * This method returns the value of the database column
     * cust_msg_push.cust_id
     * 
     * @return the value of cust_msg_push.cust_id
     * @mbggenerated
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column cust_msg_push.cust_id
     * 
     * @param custId the value for cust_msg_push.cust_id
     * @mbggenerated
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method returns the value of the database column
     * cust_msg_push.tag_name
     * 
     * @return the value of cust_msg_push.tag_name
     * @mbggenerated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column cust_msg_push.tag_name
     * 
     * @param tagName the value for cust_msg_push.tag_name
     * @mbggenerated
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method returns the value of the database column
     * cust_msg_push.message_type
     * 
     * @return the value of cust_msg_push.message_type
     * @mbggenerated
     */
    public Integer getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column cust_msg_push.message_type
     * 
     * @param messageType the value for cust_msg_push.message_type
     * @mbggenerated
     */
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }

    /**
     * This method returns the value of the database column
     * cust_msg_push.message_layout
     * 
     * @return the value of cust_msg_push.message_layout
     * @mbggenerated
     */
    public Integer getMessageLayout() {
        return messageLayout;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column cust_msg_push.message_layout
     * 
     * @param messageLayout the value for cust_msg_push.message_layout
     * @mbggenerated
     */
    public void setMessageLayout(Integer messageLayout) {
        this.messageLayout = messageLayout;
    }

    /**
     * This method returns the value of the database column
     * cust_msg_push.message_title
     * 
     * @return the value of cust_msg_push.message_title
     * @mbggenerated
     */
    public String getMessageTitle() {
        return messageTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column cust_msg_push.message_title
     * 
     * @param messageTitle the value for cust_msg_push.message_title
     * @mbggenerated
     */
    public void setMessageTitle(String messageTitle) {
        this.messageTitle = messageTitle == null ? null : messageTitle.trim();
    }

    /**
     * This method returns the value of the database column
     * cust_msg_push.message_detail
     * 
     * @return the value of cust_msg_push.message_detail
     * @mbggenerated
     */
    public String getMessageDetail() {
        return messageDetail;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column cust_msg_push.message_detail
     * 
     * @param messageDetail the value for cust_msg_push.message_detail
     * @mbggenerated
     */
    public void setMessageDetail(String messageDetail) {
        this.messageDetail = messageDetail == null ? null : messageDetail.trim();
    }

    public Integer getStart() {
        return start;
    }

    public void setStart(Integer start) {
        this.start = start;
    }

    public Integer getEnd() {
        return end;
    }

    public void setEnd(Integer end) {
        this.end = end;
    }

    public String getMessageIcon() {
        return messageIcon;
    }

    public void setMessageIcon(String messageIcon) {
        this.messageIcon = messageIcon;
    }

}
