package com.zhongan.icare.message.push.dao.dataobject;

import java.util.Date;

import com.zhongan.health.common.share.bean.BaseDataObject;

public class MailLogDO extends BaseDataObject {
    private static final long serialVersionUID = 1502689542216L;

    /**
     * 标题
     *
     * @mbggenerated
     */
    private String            title;

    /**
     * 模板
     *
     * @mbggenerated
     */
    private String            templateNo;

    /**
     * 发送的参数
     *
     * @mbggenerated
     */
    private String            param;

    /**
     * 发送方名称
     *
     * @mbggenerated
     */
    private String            senderName;

    /**
     * 发送方邮箱
     *
     * @mbggenerated
     */
    private String            fromMail;

    /**
     * 接受方邮箱列表
     *
     * @mbggenerated
     */
    private String            toMails;

    /**
     * 抄送到邮箱列表
     *
     * @mbggenerated
     */
    private String            ccMails;

    /**
     * 秘密抄送到邮箱列表
     *
     * @mbggenerated
     */
    private String            bccMails;

    /**
     * 附件
     *
     * @mbggenerated
     */
    private String            mailAttachment;

    private Integer           sendType;
    private Long              batchId;
    private Date              sendTime;
    /**
     * 短信发送返回的code
     *
     * @mbggenerated
     */
    private String            resultCode;

    /**
     * 短信发送返回的message
     *
     * @mbggenerated
     */
    private String            resultMessage;

    public String getResultCode() {
        return resultCode;
    }

    public void setResultCode(String resultCode) {
        this.resultCode = resultCode;
    }

    public String getResultMessage() {
        return resultMessage;
    }

    public void setResultMessage(String resultMessage) {
        this.resultMessage = resultMessage;
    }

    public Date getSendTime() {
        return sendTime;
    }

    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    public Long getBatchId() {
        return batchId;
    }

    public void setBatchId(Long batchId) {
        this.batchId = batchId;
    }

    public Integer getSendType() {
        return sendType;
    }

    public void setSendType(Integer sendType) {
        this.sendType = sendType;
    }

    /**
     * This method returns the value of the database column mail_log.title
     *
     * @return the value of mail_log.title
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column mail_log.title
     *
     * @param title the value for mail_log.title
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method returns the value of the database column mail_log.template_no
     *
     * @return the value of mail_log.template_no
     * @mbggenerated
     */
    public String getTemplateNo() {
        return templateNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column mail_log.template_no
     *
     * @param templateNo the value for mail_log.template_no
     * @mbggenerated
     */
    public void setTemplateNo(String templateNo) {
        this.templateNo = templateNo == null ? null : templateNo.trim();
    }

    /**
     * This method returns the value of the database column mail_log.param
     *
     * @return the value of mail_log.param
     * @mbggenerated
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column mail_log.param
     *
     * @param param the value for mail_log.param
     * @mbggenerated
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method returns the value of the database column mail_log.sender_name
     *
     * @return the value of mail_log.sender_name
     * @mbggenerated
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column mail_log.sender_name
     *
     * @param senderName the value for mail_log.sender_name
     * @mbggenerated
     */
    public void setSenderName(String senderName) {
        this.senderName = senderName == null ? null : senderName.trim();
    }

    /**
     * This method returns the value of the database column mail_log.from_mail
     *
     * @return the value of mail_log.from_mail
     * @mbggenerated
     */
    public String getFromMail() {
        return fromMail;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column mail_log.from_mail
     *
     * @param fromMail the value for mail_log.from_mail
     * @mbggenerated
     */
    public void setFromMail(String fromMail) {
        this.fromMail = fromMail == null ? null : fromMail.trim();
    }

    /**
     * This method returns the value of the database column mail_log.to_mails
     *
     * @return the value of mail_log.to_mails
     * @mbggenerated
     */
    public String getToMails() {
        return toMails;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column mail_log.to_mails
     *
     * @param toMails the value for mail_log.to_mails
     * @mbggenerated
     */
    public void setToMails(String toMails) {
        this.toMails = toMails == null ? null : toMails.trim();
    }

    /**
     * This method returns the value of the database column mail_log.cc_mails
     *
     * @return the value of mail_log.cc_mails
     * @mbggenerated
     */
    public String getCcMails() {
        return ccMails;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column mail_log.cc_mails
     *
     * @param ccMails the value for mail_log.cc_mails
     * @mbggenerated
     */
    public void setCcMails(String ccMails) {
        this.ccMails = ccMails == null ? null : ccMails.trim();
    }

    /**
     * This method returns the value of the database column mail_log.bcc_mails
     *
     * @return the value of mail_log.bcc_mails
     * @mbggenerated
     */
    public String getBccMails() {
        return bccMails;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column mail_log.bcc_mails
     *
     * @param bccMails the value for mail_log.bcc_mails
     * @mbggenerated
     */
    public void setBccMails(String bccMails) {
        this.bccMails = bccMails == null ? null : bccMails.trim();
    }

    /**
     * This method returns the value of the database column
     * mail_log.mail_attachment
     *
     * @return the value of mail_log.mail_attachment
     * @mbggenerated
     */
    public String getMailAttachment() {
        return mailAttachment;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column mail_log.mail_attachment
     *
     * @param mailAttachment the value for mail_log.mail_attachment
     * @mbggenerated
     */
    public void setMailAttachment(String mailAttachment) {
        this.mailAttachment = mailAttachment == null ? null : mailAttachment.trim();
    }

}
