package com.zhongan.icare.message.push.dao.dataobject;

import com.zhongan.health.common.share.bean.BaseDataObject;

public class MsgPushDetailDO extends BaseDataObject {
    private Long    custId;

    private String  tagName;

    private String  messageTitle;

    private Integer messageStatus;

    private Integer messageType;

    private Integer messageLayout;

    private String  messageDetail;

    private String  messageIcon;

    private String  msgTime;

    private Long    orgId;

    private Integer start;

    private Integer end;

    /**
     * This method returns the value of the database column
     * msg_push_detail.cust_id
     * 
     * @return the value of msg_push_detail.cust_id
     * @mbggenerated
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column msg_push_detail.cust_id
     * 
     * @param custId the value for msg_push_detail.cust_id
     * @mbggenerated
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method returns the value of the database column
     * msg_push_detail.tag_name
     * 
     * @return the value of msg_push_detail.tag_name
     * @mbggenerated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column msg_push_detail.tag_name
     * 
     * @param tagName the value for msg_push_detail.tag_name
     * @mbggenerated
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method returns the value of the database column
     * msg_push_detail.message_title
     * 
     * @return the value of msg_push_detail.message_title
     * @mbggenerated
     */
    public String getMessageTitle() {
        return messageTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column msg_push_detail.message_title
     * 
     * @param messageTitle the value for msg_push_detail.message_title
     * @mbggenerated
     */
    public void setMessageTitle(String messageTitle) {
        this.messageTitle = messageTitle == null ? null : messageTitle.trim();
    }

    /**
     * This method returns the value of the database column
     * msg_push_detail.message_status
     * 
     * @return the value of msg_push_detail.message_status
     * @mbggenerated
     */
    public Integer getMessageStatus() {
        return messageStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column msg_push_detail.message_status
     * 
     * @param messageStatus the value for msg_push_detail.message_status
     * @mbggenerated
     */
    public void setMessageStatus(Integer messageStatus) {
        this.messageStatus = messageStatus;
    }

    /**
     * This method returns the value of the database column
     * msg_push_detail.message_type
     * 
     * @return the value of msg_push_detail.message_type
     * @mbggenerated
     */
    public Integer getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column msg_push_detail.message_type
     * 
     * @param messageType the value for msg_push_detail.message_type
     * @mbggenerated
     */
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }

    /**
     * This method returns the value of the database column
     * msg_push_detail.message_layout
     * 
     * @return the value of msg_push_detail.message_layout
     * @mbggenerated
     */
    public Integer getMessageLayout() {
        return messageLayout;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column msg_push_detail.message_layout
     * 
     * @param messageLayout the value for msg_push_detail.message_layout
     * @mbggenerated
     */
    public void setMessageLayout(Integer messageLayout) {
        this.messageLayout = messageLayout;
    }

    /**
     * This method returns the value of the database column
     * msg_push_detail.message_detail
     * 
     * @return the value of msg_push_detail.message_detail
     * @mbggenerated
     */
    public String getMessageDetail() {
        return messageDetail;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column msg_push_detail.message_detail
     * 
     * @param messageDetail the value for msg_push_detail.message_detail
     * @mbggenerated
     */
    public void setMessageDetail(String messageDetail) {
        this.messageDetail = messageDetail == null ? null : messageDetail.trim();
    }

    public Integer getStart() {
        return start;
    }

    public void setStart(Integer start) {
        this.start = start;
    }

    public Integer getEnd() {
        return end;
    }

    public void setEnd(Integer end) {
        this.end = end;
    }

    public String getMsgTime() {
        return msgTime;
    }

    public void setMsgTime(String msgTime) {
        this.msgTime = msgTime;
    }

    public String getMessageIcon() {
        return messageIcon;
    }

    public void setMessageIcon(String messageIcon) {
        this.messageIcon = messageIcon;
    }

    public Long getOrgId() {
        return orgId;
    }

    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

}
