package com.zhongan.icare.message.push.dao.dataobject;

import com.zhongan.health.common.share.bean.BaseDataObject;

public class MsgPushCustTagDO extends BaseDataObject {
    private Long custId;

    private Long tagId;

    /**
     * This method returns the value of the database column cust_msg_push_cust_tag.cust_id
     *
     * @return the value of cust_msg_push_cust_tag.cust_id
     *
     * @mbggenerated
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_msg_push_cust_tag.cust_id
     *
     * @param custId the value for cust_msg_push_cust_tag.cust_id
     *
     * @mbggenerated
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method returns the value of the database column cust_msg_push_cust_tag.tag_id
     *
     * @return the value of cust_msg_push_cust_tag.tag_id
     *
     * @mbggenerated
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_msg_push_cust_tag.tag_id
     *
     * @param tagId the value for cust_msg_push_cust_tag.tag_id
     *
     * @mbggenerated
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }
}