package com.zhongan.icare.message.push.dao.dataobject;

import com.zhongan.health.common.share.bean.BaseDataObject;

public class PushRequestDataDO extends BaseDataObject
{
    private static final long serialVersionUID = 1487068606117L;

    /**
     * 类型（1：发送单条给单个人，2：发送单条给第三方，3：发送一条给多人，4：发送一条给所有人，5：发送多条给多人）
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * 数据
     *
     * @mbggenerated
     */
    private String data;

    /**
     * 数据类型
     *
     * @mbggenerated
     */
    private String dataClass;

    /**
     * This method returns the value of the database column push_request_data.type
     *
     * @return the value of push_request_data.type
     * @mbggenerated
     */
    public Integer getType()
    {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_request_data.type
     *
     * @param type the value for push_request_data.type
     * @mbggenerated
     */
    public void setType(Integer type)
    {
        this.type = type;
    }

    /**
     * This method returns the value of the database column push_request_data.data
     *
     * @return the value of push_request_data.data
     * @mbggenerated
     */
    public String getData()
    {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_request_data.data
     *
     * @param data the value for push_request_data.data
     * @mbggenerated
     */
    public void setData(String data)
    {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method returns the value of the database column push_request_data.data_class
     *
     * @return the value of push_request_data.data_class
     * @mbggenerated
     */
    public String getDataClass()
    {
        return dataClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_request_data.data_class
     *
     * @param dataClass the value for push_request_data.data_class
     * @mbggenerated
     */
    public void setDataClass(String dataClass)
    {
        this.dataClass = dataClass == null ? null : dataClass.trim();
    }
}