package com.zhongan.icare.message.push.dao.dataobject;

import com.zhongan.health.common.share.bean.BaseDataObject;
import com.zhongan.health.common.share.bean.PageDTO;

import java.util.Date;

public class PushRequestLogDO extends BaseDataObject {
    private static final long serialVersionUID = 1481255861525L;
    /**
     * 开始时间
     */
    private Date searchStartDate;

    /**
     * 结束时间
     */
    private Date searchEndDate;
    /**
     * 会员id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * 消息模板标识
     *
     * @mbggenerated
     */
    private String templateCode;

    /**
     * 组的编号
     *
     * @mbggenerated
     */
    private String groupCode;

    /**
     * 消息类型（0：透传，1：通知）
     *
     * @mbggenerated
     */
    private Integer messageType;

    /**
     * 消息展示格式（0：文本，1：文本+图片，2：超链接）
     *
     * @mbggenerated
     */
    private Integer messageLayout;

    /**
     * 消息变量数据
     *
     * @mbggenerated
     */
    private String data;

    /**
     * 模板解析后的数据
     *
     * @mbggenerated
     */
    private String templateData;

    /**
     * 状态（0：未读，1：已读）
     *
     * @mbggenerated
     */
    private Integer status;


    /**
     * 分页信息
     */
    private PageDTO page;

    public PageDTO getPage() {
        return page;
    }

    public void setPage(PageDTO page) {
        this.page = page;
    }

    /**
     * This method returns the value of the database column push_request_log.customer_id
     *
     * @return the value of push_request_log.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_request_log.customer_id
     *
     * @param customerId the value for push_request_log.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method returns the value of the database column push_request_log.template_code
     *
     * @return the value of push_request_log.template_code
     *
     * @mbggenerated
     */
    public String getTemplateCode() {
        return templateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_request_log.template_code
     *
     * @param templateCode the value for push_request_log.template_code
     *
     * @mbggenerated
     */
    public void setTemplateCode(String templateCode) {
        this.templateCode = templateCode == null ? null : templateCode.trim();
    }

    /**
     * This method returns the value of the database column push_request_log.group_code
     *
     * @return the value of push_request_log.group_code
     *
     * @mbggenerated
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_request_log.group_code
     *
     * @param groupCode the value for push_request_log.group_code
     *
     * @mbggenerated
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method returns the value of the database column push_request_log.message_type
     *
     * @return the value of push_request_log.message_type
     *
     * @mbggenerated
     */
    public Integer getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_request_log.message_type
     *
     * @param messageType the value for push_request_log.message_type
     *
     * @mbggenerated
     */
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }

    /**
     * This method returns the value of the database column push_request_log.message_layout
     *
     * @return the value of push_request_log.message_layout
     *
     * @mbggenerated
     */
    public Integer getMessageLayout() {
        return messageLayout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_request_log.message_layout
     *
     * @param messageLayout the value for push_request_log.message_layout
     *
     * @mbggenerated
     */
    public void setMessageLayout(Integer messageLayout) {
        this.messageLayout = messageLayout;
    }

    /**
     * This method returns the value of the database column push_request_log.data
     *
     * @return the value of push_request_log.data
     *
     * @mbggenerated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_request_log.data
     *
     * @param data the value for push_request_log.data
     *
     * @mbggenerated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method returns the value of the database column push_request_log.template_data
     *
     * @return the value of push_request_log.template_data
     *
     * @mbggenerated
     */
    public String getTemplateData() {
        return templateData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_request_log.template_data
     *
     * @param templateData the value for push_request_log.template_data
     *
     * @mbggenerated
     */
    public void setTemplateData(String templateData) {
        this.templateData = templateData == null ? null : templateData.trim();
    }

    /**
     * This method returns the value of the database column push_request_log.status
     *
     * @return the value of push_request_log.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_request_log.status
     *
     * @param status the value for push_request_log.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    public Date getSearchStartDate() {
        return searchStartDate;
    }

    public void setSearchStartDate(Date searchStartDate) {
        this.searchStartDate = searchStartDate;
    }

    public Date getSearchEndDate() {
        return searchEndDate;
    }

    public void setSearchEndDate(Date searchEndDate) {
        this.searchEndDate = searchEndDate;
    }
}