package com.zhongan.icare.message.push.dao.dataobject;

import com.zhongan.health.common.share.bean.BaseDataObject;

import java.util.Date;

public class PushSendLogDO extends BaseDataObject {
    private static final long serialVersionUID = 1481255861526L;

    /**
     * 请求消息的id
     *
     * @mbggenerated
     */
    private Long requestLogId;

    /**
     * 消息发送用的百度标识
     *
     * @mbggenerated
     */
    private String baiduChannel;

    /**
     * 消息发送用的百度设备类型
     *
     * @mbggenerated
     */
    private Integer deviceType;

    /**
     * 消息发送用的百度通知数据内容(完整JSON)
     *
     * @mbggenerated
     */
    private String messageContent;

    /**
     * 消息发送时间
     *
     * @mbggenerated
     */
    private Date sendTime;

    /**
     * 百度返回的消息id
     *
     * @mbggenerated
     */
    private String baiduMsgid;

    /**
     * This method returns the value of the database column push_send_log.request_log_id
     *
     * @return the value of push_send_log.request_log_id
     *
     * @mbggenerated
     */
    public Long getRequestLogId() {
        return requestLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_send_log.request_log_id
     *
     * @param requestLogId the value for push_send_log.request_log_id
     *
     * @mbggenerated
     */
    public void setRequestLogId(Long requestLogId) {
        this.requestLogId = requestLogId;
    }

    /**
     * This method returns the value of the database column push_send_log.baidu_channel
     *
     * @return the value of push_send_log.baidu_channel
     *
     * @mbggenerated
     */
    public String getBaiduChannel() {
        return baiduChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_send_log.baidu_channel
     *
     * @param baiduChannel the value for push_send_log.baidu_channel
     *
     * @mbggenerated
     */
    public void setBaiduChannel(String baiduChannel) {
        this.baiduChannel = baiduChannel == null ? null : baiduChannel.trim();
    }

    /**
     * This method returns the value of the database column push_send_log.device_type
     *
     * @return the value of push_send_log.device_type
     *
     * @mbggenerated
     */
    public Integer getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_send_log.device_type
     *
     * @param deviceType the value for push_send_log.device_type
     *
     * @mbggenerated
     */
    public void setDeviceType(Integer deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method returns the value of the database column push_send_log.message_content
     *
     * @return the value of push_send_log.message_content
     *
     * @mbggenerated
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_send_log.message_content
     *
     * @param messageContent the value for push_send_log.message_content
     *
     * @mbggenerated
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent == null ? null : messageContent.trim();
    }

    /**
     * This method returns the value of the database column push_send_log.send_time
     *
     * @return the value of push_send_log.send_time
     *
     * @mbggenerated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_send_log.send_time
     *
     * @param sendTime the value for push_send_log.send_time
     *
     * @mbggenerated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method returns the value of the database column push_send_log.baidu_msgid
     *
     * @return the value of push_send_log.baidu_msgid
     *
     * @mbggenerated
     */
    public String getBaiduMsgid() {
        return baiduMsgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_send_log.baidu_msgid
     *
     * @param baiduMsgid the value for push_send_log.baidu_msgid
     *
     * @mbggenerated
     */
    public void setBaiduMsgid(String baiduMsgid) {
        this.baiduMsgid = baiduMsgid == null ? null : baiduMsgid.trim();
    }
}