package com.zhongan.icare.message.push.dao.dataobject;

import com.zhongan.health.common.share.bean.BaseDataObject;

public class MsgPushRelDO extends BaseDataObject {
    private Long    custId;

    private Long    orgId;

    private Integer deviceType;

    private String  channelId;

    /**
     * This method returns the value of the database column
     * cust_msg_push_rel.cust_id
     * 
     * @return the value of cust_msg_push_rel.cust_id
     * @mbggenerated
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column cust_msg_push_rel.cust_id
     * 
     * @param custId the value for cust_msg_push_rel.cust_id
     * @mbggenerated
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method returns the value of the database column
     * cust_msg_push_rel.org_id
     * 
     * @return the value of cust_msg_push_rel.org_id
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column cust_msg_push_rel.org_id
     * 
     * @param orgId the value for cust_msg_push_rel.org_id
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method returns the value of the database column
     * cust_msg_push_rel.device_type
     * 
     * @return the value of cust_msg_push_rel.device_type
     * @mbggenerated
     */
    public Integer getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column cust_msg_push_rel.device_type
     * 
     * @param deviceType the value for cust_msg_push_rel.device_type
     * @mbggenerated
     */
    public void setDeviceType(Integer deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method returns the value of the database column
     * cust_msg_push_rel.channel_id
     * 
     * @return the value of cust_msg_push_rel.channel_id
     * @mbggenerated
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column cust_msg_push_rel.channel_id
     * 
     * @param channelId the value for cust_msg_push_rel.channel_id
     * @mbggenerated
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }
}
